var Noopath = require("./Noopath")
Noopath.setPath("/var/www/node/noopath")
Noopath.setIgnorePaths(["/var/www/node/noopath/nbproject/"])
Noopath.setIgnoreExtensions(["json"])
console.log(Noopath.getConfig().var.www.node)